# Generated by Django 4.2.16 on 2024-11-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="short_description",
            field=models.TextField(default="Description"),
        ),
    ]
