# Generated by Django 4.2.16 on 2024-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="short_desc",
            field=models.CharField(default="No Description Provided!", max_length=255),
        ),
    ]
